version: "3.8"

services:
  mongo:
    container_name: mongo_db_to_tests
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - testdb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
volumes:
    testdb: