

name: Run Tests
on: 
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: go/src/github.com/rrgaya/mongodb-wrapper-go
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
      with:
        path: 'go/src/github.com/rrgaya/mongodb-wrapper-go'
    - name: Run Vet
      run: |
        go vet ./...
    - name: Run Lint
      run: |
        go install golang.org/x/lint/golint@latest
        golint .
    - name: Run Tests
      run: |
        go test -v ./...
    - name: Run Tests with Race Detector
      run: |
        go test -v -race ./...