# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_mongo:
    runs-on: ubuntu-latest
    container: golang:1.19-bullseye

    services:
      mongodb:
        image: rrgaya/mongodb
        options: ->
          - test "mongo localhost:27017/test --quiet --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
          # interval: 10s
          # timeout: 5s
          # retries: 5
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # - name: Build
      #     run: go build -v ./...

      - name: Tests Unitários
        run: go test -v ./...
        env:
          CI: True
