name: MongoDBTest
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19-bullseye
    services:
      mongodb:
        image: rrgaya/mongodb
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password123
        #   POSTGRES_PASSWORD: minhareceita
        #   POSTGRES_USER: minhareceita
        #   POSTGRES_DB: minhareceita
        # options: >-
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - run: "go test --race ./..."
        # env:
        #   TEST_DATABASE_URL: postgres://minhareceita:minhareceita@postgres:5432/minhareceita?sslmode=disable