name: MongoDBTest
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19-bullseye
    services:
      mongodb:
        image: rrgaya/mongodb
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password@123
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - run: "go test --race ./..."
        # env:
        #   TEST_DATABASE_URL: postgres://admin:password@123@mongodb:5432/minhareceita?sslmode=disable